### ISSUE TITLE
The node can't run and the log shows "panic: UnmarshalJSON cannot decode empty bytes"

### ISSUE THREAD

**Issue by Jackwumingjie** [xpladev/xpla#45]
go:1.18.8
node: v1.1.2
error log:
<img width="1270" alt="企业微信截图_c09017ac-af55-4eea-886b-eb49c5ac28ba" src="https://user-images.githubusercontent.com/39093109/203018079-e01dd034-d119-4e2f-8f1a-f00e9aaca12c.png">

**Comment by caramis** [comment]
Which genesis.json did you use ??
