### ISSUE TITLE
`payer` field from /cosmos/tx/v1beta1/txs is emtpy

### ISSUE THREAD

**Issue by Xkimnt** [xpladev/xpla#98]
I tried to use /cosmos/tx/v1beta1/txs/:tx_hash to get the transaction detail and I use `payer` field from response to determine which address paid the transaction fee. For some transactions, the `payer` field is empty from rpc response, for example,

`curl --location 'https://dimension-lcd.xpla.dev/cosmos/tx/v1beta1/txs/43EF7F027064C3D12195297A579500397B949EA9A9B3B2B33E65FF4AD9118E77'`

![NS@FD21T{ZOJ(8`)Q3 7T%V](https://github.com/xpladev/xpla/assets/47097304/1cc21010-2848-48c8-8d19-0473c9df43b2)

The `payer` field is empty in this case. I'm new to the blockchain, so is that an expected behavior or just some blockchain node issue? If the `payer` field is empty, then how can I determine which address paid the transaction fee?

**Comment by JoowonYun** [comment]
This field is used when the fee payer is an account other than the sender. The Tx is not displayed because the fee payer is the sender.

**Comment by Xkimnt** [comment]
> This field is used when the fee payer is an account other than the sender. The Tx is not displayed because the fee payer is the sender.

Thanks for your reply.  Basically I want to get the actual `fee payer` from the http response.
From your comment, if I understand correctly, if the `payer` field is empty, then in this transaction the sender would pay the fee otherwise the value from `payer` is the actual fee payer. From the http response, in order to get the `sender`, what I can think of now is looping through the `logs` and `messages`.

<img width="656" alt="截屏2023-11-02 11 40 20" src="https://github.com/xpladev/xpla/assets/47097304/38ff2db6-090b-47d5-86d9-eba47e831875">
<img width="634" alt="截屏2023-11-02 11 40 44" src="https://github.com/xpladev/xpla/assets/47097304/a7250d6f-d54c-4e56-9638-c4081a0ba951">

From my experience, the response schema of `logs` and `messages` would vary with the cosmos modules and for some messages like vote, the response even does not have a `sender` field. Considering the fact that there maybe multiple messages in the transaction, does that mean in order to get the actual `fee payer`,  I need to loop every message and handle each specific response schema according to message type?

I'm not sure if there is something I miss here, this seems kind of complicated.

**Comment by JoowonYun** [comment]
Yes, it may be slightly different depending on the cosmos-sdk version. 
Fields such as from_address are different for each msg, so it is most accurate to look at the signature. You can extract the address from the corresponding pubkey.

**Comment by Xkimnt** [comment]
> Yes, it may be slightly different depending on the cosmos-sdk version. Fields such as from_address are different for each msg, so it is most accurate to look at the signature. You can extract the address from the corresponding pubkey.

Thanks! So if I understand correctly, in order to get the actual `fee payer`, the process is checking `payer` field first, if `payer` is not empty, then the value of `payer` is the actual `fee payer`. Otherwise, extracting the address from public key in the http response which is the actual `fee payer`.

I found that there are some functions in `xpla.js` that seem to get the address from the public key. I wonder is the function used here would be the right one to handle the problem?
```javascript
import { SimplePublicKey } from '@xpla/xpla.js';
const publicKey = 'Aj7PGfjlRoxoX19+ZQrVn5ZFhi6IHLfSBPB+QBf7R/mh';
const spk = SimplePublicKey.fromData({
  key: publicKey,
  '@type': '/ethermint.crypto.v1.ethsecp256k1.PubKey',
});
console.log(spk.address());
```

**Comment by JoowonYun** [comment]
> > Yes, it may be slightly different depending on the cosmos-sdk version. Fields such as from_address are different for each msg, so it is most accurate to look at the signature. You can extract the address from the corresponding pubkey.
> 
> Thanks! So if I understand correctly, in order to get the actual `fee payer`, the process is checking `payer` field first, if `payer` is not empty, then the value of `payer` is the actual `fee payer`. Otherwise, extracting the address from public key in the http response which is the actual `fee payer`.
> 
> I found that there are some functions in `xpla.js` that seem to get the address from the public key. I wonder is the function used here would be the right one to handle the problem?
> 
> ```js
> import { SimplePublicKey } from '@xpla/xpla.js';
> const publicKey = 'Aj7PGfjlRoxoX19+ZQrVn5ZFhi6IHLfSBPB+QBf7R/mh';
> const spk = SimplePublicKey.fromData({
>   key: publicKey,
>   '@type': '/ethermint.crypto.v1.ethsecp256k1.PubKey',
> });
> console.log(spk.address());
> ```

`spk.address()` is right. However, we are not sure that the corresponding public key is `/ethermint.crypto.v1.ethsecp256k1.PubKey`. It is recommended to obtain the entire public key and decode it.

**Comment by Xkimnt** [comment]
> > > Yes, it may be slightly different depending on the cosmos-sdk version. Fields such as from_address are different for each msg, so it is most accurate to look at the signature. You can extract the address from the corresponding pubkey.
> > 
> > 
> > Thanks! So if I understand correctly, in order to get the actual `fee payer`, the process is checking `payer` field first, if `payer` is not empty, then the value of `payer` is the actual `fee payer`. Otherwise, extracting the address from public key in the http response which is the actual `fee payer`.
> > I found that there are some functions in `xpla.js` that seem to get the address from the public key. I wonder is the function used here would be the right one to handle the problem?
> > ```js
> > import { SimplePublicKey } from '@xpla/xpla.js';
> > const publicKey = 'Aj7PGfjlRoxoX19+ZQrVn5ZFhi6IHLfSBPB+QBf7R/mh';
> > const spk = SimplePublicKey.fromData({
> >   key: publicKey,
> >   '@type': '/ethermint.crypto.v1.ethsecp256k1.PubKey',
> > });
> > console.log(spk.address());
> > ```
> 
> `spk.address()` is right. However, we are not sure that the corresponding public key is `/ethermint.crypto.v1.ethsecp256k1.PubKey`. It is recommended to obtain the entire public key and decode it.

I understand. Thanks for the explanation!
